#!/bin/bash

orignal='#!/bin/bash

echo "Starting Services"

userName=$(whoami)
direct=$PWD

echo "Starting SmallShell(sS)"

sleep 1

clear

sleep 1

while [ 1 ];
do
	printf "$userName@SmallShell:$direct&& "
	read Command
	$Command
	direct=$PWD
done'
CheckFile="./sS"

FileCheck=$(cat $CheckFile)

if [ $FileCheck == $original ];
then
	echo okay
	exit
else
	echo not okay overwriting
	echo $original > $FileCheck
	echo "finished"
fi

